name: axolotl
summary: A signal client.
description: |
  Axolotl is a cross-platform Signal client
grade: stable
confinement: strict
base: core20
icon: snap/gui/axolotl.png
version: "1.6.0"
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
parts:
  axolotl:
    # https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/v1/go.py
    plugin: go
    source: .
    build-packages:
      - gcc
      - g++
    stage-packages:
      # These are required for Electron
      - libasound2
      - libgconf-2-4
      - libnss3
      - libx11-xcb1
      - libxss1
      - libxtst6
    override-build: |
      snapcraftctl build
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/lib

  axolotl-web:
    plugin: npm
    source: ./axolotl-web
    npm-node-version: 18.12.0
    build-environment:
      - npm_config_unsafe_perm: "true"
      - SUDO_UID: "0"
      - SUDO_GID: "0"
      - SUDO_USER: root
    organize:
      ../build/dist: "bin/axolotl-web"
    override-build: |
      mkdir -p /root/parts/axolotl-web/install
      if echo $(dpkg --print-architecture)|grep -q 'amd64'; then curl -s https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-x64.tar.gz | tar xzf - -C $SNAPCRAFT_PART_SRC/../install --strip-components=1 ; fi
      if echo $(dpkg --print-architecture)|grep -q 'arm64'; then curl -s https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-arm64.tar.gz | tar xzf - -C $SNAPCRAFT_PART_SRC/../install --strip-components=1 ; fi
      if echo $(dpkg --print-architecture)|grep -q 'armhf'; then curl -s https://nodejs.org/dist/v16.13.1/node-v16.13.1-linux-armv7l.tar.gz | tar xzf - -C $SNAPCRAFT_PART_SRC/../install --strip-components=1 ; fi
      export PATH=$SNAPCRAFT_PART_SRC/../install/bin/:$PATH
      npm config set unsafe-perm true
      npm install -g yarn
      yarn install
      yarn run build
      cp -r dist ../install/bin/axolotl-web
    stage:
      - bin/axolotl-web

plugs:
  browser-sandbox:
    allow-sandbox: false
    interface: browser-support

apps:
  axolotl:
    command: bin/axolotl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      XDG_DATA_HOME: $SNAP_USER_DATA
    # This is required for Electron
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - network
      - network-bind
      - network-manager
      - pulseaudio
      - home
      - x11
      - gsettings
      - browser-sandbox
