name: axolotl
summary: A signal client.
description: |
  Axolotl is a cross-platform Signal client
grade: stable
confinement: strict
base: core20
icon: snap/gui/axolotl.png
version: "1.0.0"
architectures:
  - build-on: amd64
  - build-on: arm64
parts:
  axolotl:
    # https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/v1/go.py
    plugin: go
    source: .
    build-packages:
      - gcc
      - g++
    stage-packages:
      # These are required for Electron
      - libasound2
      - libgconf-2-4
      - libnss3
      - libx11-xcb1
      - libxss1
      - libxtst6
    override-build: |
      snapcraftctl build
      mkdir --parents $SNAPCRAFT_PART_INSTALL/usr/lib
      cp /root/go/pkg/mod/github.com/nanu-c/zkgroup*/lib/libzkgroup_linux_$(dpkg --print-architecture).so $SNAPCRAFT_PART_INSTALL/usr/lib


  axolotl-web:
    # https://github.com/snapcore/snapcraft/blob/master/snapcraft/plugins/v1/nodejs.py
    plugin: npm
    source: ./axolotl-web
    npm-node-version: 14.16.0
    build-packages:
      - npm
    override-build: |
      # Add npm to path
      export PATH=$PWD/../npm/bin:$PATH
      # Due to the confinement this runs as root, and then we need this config
      npm config set unsafe-perm true
      npm ci
      npm run build
      mkdir -p ../install/bin
      cp -r dist ../install/bin/axolotl-web
    stage:
      - bin/axolotl-web

plugs:
  browser-sandbox:
    allow-sandbox: false
    interface: browser-support

apps:
  axolotl:
    command: bin/axolotl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    # This is required for Electron
    extensions: [gnome-3-38]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - network
      - network-bind
      - network-manager
      - pulseaudio
      - home
      - x11
      - gsettings
      - browser-sandbox
