name: axolotl
summary: An signal client.
description: |
  Axolotl is a crossplattform signal client
grade: stable
confinement: strict
base: core18
icon:  snap/gui/axolotl.png
version: "0.8.8"

parts:
  axolotl:
    plugin: go
    go-importpath: github.com/nanu-c/axolotl
    source: .
    source-type: git
    build-packages:
      - gcc
      - mercurial
      - bzr
      - g++
    stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libx11-xcb1
      - libxss1
      - libxtst6
    override-build: |
      echo "This runs before build!"
      snapcraftctl build
  axolotl-web:
    plugin: nodejs
    source: ./axolotl-web
    stage: [bin/axolotl-web]
    nodejs-version: 12.18.4
    nodejs-package-manager: npm
    build-environment:
      - SUDO_UID: '0'
      - SUDO_GID: '0'
      - SUDO_USER: 'root'
    override-build: |
      export PATH=$PWD/../npm/bin:$PATH
      npm config set unsafe-perm true
      npm install
      npm install -g @vue/cli
      npm install -g @vue/cli-service
      npm install -g @vue/cli-plugin-babel
      npm install -g @vue/cli-plugin-eslint
      npm run build || true
      mkdir -p ../install/bin/ || true
      cp -r dist ../install/bin/axolotl-web
    organize:
      axolotl-web/dist: bin/axolotl-web
plugs:
  browser-sandbox:
    allow-sandbox:  false
    interface: browser-support

apps:
  axolotl:
    command: bin/axolotl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
    extensions: [gnome-3-28]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - network
      - network-bind
      - network-manager
      - pulseaudio
      - home
      - x11
      - gsettings
      - browser-sandbox

    # plugs: ["desktop", "desktop-legacy", "home", "x11", "unity7", "network-observe", "browser-support", "network", "gsettings", "pulseaudio", "opengl"]
