#!/bin/sh
# postinst script for axolotl

set -e

case "$1" in
    configure)
    ln -sf /usr/share/axolotl/axolotl /usr/bin/axolotl
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
