name: Axolotl release pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-artifacts
      - name: Get git tag version
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Create draft GitHub release page
        id: create_release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ steps.get_version.outputs.version }}
          draft: true
          prerelease: false
          files: |
            **/*.click
            **/*.deb
            **/*.AppImage
